# Generated by Django 6.0.5 on 2026-05-23 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('group', models.CharField(max_length=20)),
                ('rarity', models.CharField(choices=[('SSR', 'SSR'), ('SR', 'SR'), ('R', 'R'), ('N', 'N')], max_length=3)),
                ('emoji', models.CharField(max_length=5)),
                ('quote', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('points', models.IntegerField(default=0)),
                ('correct', models.IntegerField(default=0)),
                ('wrong', models.IntegerField(default=0)),
                ('collection', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chinese', models.CharField(max_length=20)),
                ('english', models.CharField(max_length=50)),
            ],
        ),
    ]
