# Generated by Django 6.0.5 on 2026-05-27 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='part_of_speech',
            field=models.CharField(choices=[('n.', 'Noun'), ('v.', 'Verb'), ('adj.', 'Adjective'), ('adv.', 'Adverb')], default='n.', max_length=5),
        ),
    ]
