// 前端備用 CARDS 資料（從 API 拿到時會替換）
const CARDS_LOCAL = [
  {card_id:'bts1',emoji:'🐰',name:'Jungkook',group:'BTS',rarity:'SSR',quote:'Still With You'},
  {card_id:'bts2',emoji:'🐱',name:'V',group:'BTS',rarity:'SR',quote:'Singularity'},
  {card_id:'bts3',emoji:'🐿',name:'Suga',group:'BTS',rarity:'SR',quote:'Agust D'},
  {card_id:'bts4',emoji:'🐥',name:'J-Hope',group:'BTS',rarity:'R',quote:'Chicken Noodle Soup'},
  {card_id:'bts5',emoji:'🐨',name:'RM',group:'BTS',rarity:'R',quote:'Mono'},
  {card_id:'bts6',emoji:'🐹',name:'Jimin',group:'BTS',rarity:'N',quote:'Filter'},
  {card_id:'bts7',emoji:'🐻',name:'Jin',group:'BTS',rarity:'N',quote:'Moon'},
  {card_id:'tw1',emoji:'🍭',name:'Nayeon',group:'TWICE',rarity:'SSR',quote:'FANCY'},
  {card_id:'tw2',emoji:'🌺',name:'Jihyo',group:'TWICE',rarity:'SR',quote:'Signal'},
  {card_id:'tw3',emoji:'🍑',name:'Momo',group:'TWICE',rarity:'SR',quote:'Feel Special'},
  {card_id:'tw4',emoji:'☁️',name:'Sana',group:'TWICE',rarity:'R',quote:'What is Love?'},
  {card_id:'tw5',emoji:'🌸',name:'Jeongyeon',group:'TWICE',rarity:'R',quote:'Scientist'},
  {card_id:'tw6',emoji:'🎀',name:'Dahyun',group:'TWICE',rarity:'R',quote:'YES or YES'},
  {card_id:'tw7',emoji:'🍀',name:'Chaeyoung',group:'TWICE',rarity:'N',quote:'Alcohol-Free'},
  {card_id:'tw8',emoji:'🌙',name:'Mina',group:'TWICE',rarity:'N',quote:'Likey'},
  {card_id:'tw9',emoji:'🦋',name:'Tzuyu',group:'TWICE',rarity:'N',quote:'Cheer Up'},
  {card_id:'txt1',emoji:'🌌',name:'Yeonjun',group:'TXT',rarity:'SSR',quote:'Run Away'},
  {card_id:'txt2',emoji:'🔮',name:'Soobin',group:'TXT',rarity:'SR',quote:'0X1=LOVESONG'},
  {card_id:'txt3',emoji:'🌊',name:'Beomgyu',group:'TXT',rarity:'SR',quote:'Eternally'},
  {card_id:'txt4',emoji:'🌙',name:'Taehyun',group:'TXT',rarity:'R',quote:'Blue Hour'},
  {card_id:'txt5',emoji:'🐦',name:'Huening Kai',group:'TXT',rarity:'N',quote:'Crown'},
  {card_id:'bp1',emoji:'🌹',name:'JENNIE',group:'BLACKPINK',rarity:'SSR',quote:'SOLO'},
  {card_id:'bp2',emoji:'🦋',name:'LISA',group:'BLACKPINK',rarity:'SR',quote:'LALISA'},
  {card_id:'bp3',emoji:'🌸',name:'JISOO',group:'BLACKPINK',rarity:'R',quote:'FLOWER'},
  {card_id:'bp4',emoji:'💎',name:'ROSÉ',group:'BLACKPINK',rarity:'SR',quote:'On The Ground'},
  {card_id:'iu1',emoji:'🎵',name:'IU (Celebrity)',group:'IU',rarity:'SSR',quote:'Celebrity'},
  {card_id:'iu2',emoji:'🌺',name:'IU (Palette)',group:'IU',rarity:'SR',quote:'Palette'},
  {card_id:'iu3',emoji:'🌙',name:'IU (Through the Night)',group:'IU',rarity:'SR',quote:'Through the Night'},
  {card_id:'iu4',emoji:'🎀',name:'IU (BBIBBI)',group:'IU',rarity:'R',quote:'BBIBBI'},
  {card_id:'iu5',emoji:'🍀',name:'IU (Twenty-Three)',group:'IU',rarity:'N',quote:'Twenty-Three'},
];
